from abc import ABC, abstractmethod
from src.modules.institutional.domain.entities.lead import Lead

class ILeadRepository(ABC):
    @abstractmethod
    def create(self, lead:Lead) -> None: ...

    def read_all(self) -> list[Lead]: ...

    def read_by_id(self, id:str) -> Lead: ...

    def read_by_email(self, email:str) -> list[Lead]: ...

    def update(self, id:str, lead:Lead) -> None: ...
    
    def delete(self, id:str) -> None: ...