from src.modules.personal_finance.data.repositories.personal_finance_repository import PersonalFinanceRepository
from src.modules.personal_finance.domain.use_cases.generate_finance_report_use_case import GeneratePersonalFinanceReportUseCase
from src.modules.personal_finance.ui.controllers.local_personal_finance_controller import LocalPersonalFinanceController

repository = PersonalFinanceRepository()
use_case = GeneratePersonalFinanceReportUseCase(repository=repository)
controller = LocalPersonalFinanceController(use_case=use_case)
